尝试yq

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -31,6 +31,7 @@ jobs:
           wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O ~/bin/yq
           chmod +x ~/bin/yq
           echo "$HOME/bin" >> $GITHUB_PATH
+          yq
           
 
       - name: downloading addons
@@ -209,7 +210,7 @@ jobs:
         run: |
                   
                   find ./addons -type f \( -name "README.md" -o -name "DOCS.md" \) -print0 | xargs -0 -P 5 -I {} sh -c '
-                    timeout 90s ai-markdown-translator -i "{}" -o "{}" -l "Chinese" "https://free.v36.cm" --api-key "sk-RAtilFmZ7FZhulUvA145E50b64B34f32B10a6631625e2e05" --model "gpt-3.5-turbo" || echo "{} translation failed or timed out."
+                    timeout 90s ai-markdown-translator -i "{}" -o "{}" -l "Chinese" --openai-url "https://free.v36.cm" --api-key "sk-RAtilFmZ7FZhulUvA145E50b64B34f32B10a6631625e2e05" --model "gpt-3.5-turbo" || echo "{} translation failed or timed out."
                   '
 
 
